#!/bin/sh

# update server.xml
cat conf/server.xml.orig > conf/server.xml

if [ ${CATALINA_CONNECTOR_PROXYNAME} ]
then
  xmlstarlet ed --inplace --insert Server/Service/Connector[@port=8090] --type attr -n proxyName -v ${CATALINA_CONNECTOR_PROXYNAME:-} conf/server.xml
fi

if [ ${CATALINA_CONNECTOR_PROXYPORT} ]
then
  xmlstarlet ed --inplace --insert Server/Service/Connector[@port=8090] --type attr -n proxyPort -v ${CATALINA_CONNECTOR_PROXYPORT:-} conf/server.xml
fi

if [ ${CATALINA_CONNECTOR_SCHEME} ]
then
  xmlstarlet ed --inplace --insert Server/Service/Connector[@port=8090] --type attr -n scheme -v ${CATALINA_CONNECTOR_SCHEME:-} conf/server.xml
fi

# passing through sigkill to child process
# see: https://veithen.github.io/2014/11/16/sigterm-propagation.html
trap 'kill -TERM $PID' TERM INT

export CATALINA_OPTS="-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8"
export JAVA_HOME=/opt/java/
./bin/catalina.sh run &
wait $PID
trap - TERM INT
wait $PID
EXIT_STATUS=$?
